export const environment = {
    production: false,
    filterCategories: [
        'General',
        'CPU',
        'Display',
        'Camera',
        'Memory',
        'Network',
        'Connection',
        'Physical',
    ],
    filterKeys: new Map([
        ['General', ['colors', 'brand', 'os', 'battery']],
        ['CPU', ['speed', 'cores']],
        [
            'Display',
            [
                'diameter',
                'resolution',
                'technology',
                'refreshRate',
                'colorDepth',
            ],
        ],
        [
            'Camera',
            [
                'backResolution',
                'backMaxZoom',
                'frontResolution',
                'autofocus',
                'flashlight',
                'recordingMaxResolution',
            ],
        ],
        ['Memory', ['ram', 'storages']],
        ['Network', ['simType', 'dualSim', 'has5g']],
        ['Connection', ['usb', 'jack', 'wifi', 'bluetooth', 'nfc']],
        ['Physical', ['height', 'width', 'depth', 'weight']],
    ]),
    emptyFilterValues: new Map([
        ['colors', []],
        ['brand', []],
        ['os', []],
        ['battery', []],
        ['speed', []],
        ['cores', []],
        ['diameter', []],
        ['resolution', []],
        ['technology', []],
        ['refreshRate', []],
        ['colorDepth', []],
        ['backResolution', []],
        ['backMaxZoom', []],
        ['frontResolution', []],
        ['autofocus', []],
        ['flashlight', []],
        ['recordingMaxResolution', []],
        ['ram', []],
        ['storages', []],
        ['simType', []],
        ['dualSim', []],
        ['has5g', []],
        ['usb', []],
        ['jack', []],
        ['wifi', []],
        ['bluetooth', []],
        ['nfc', []],
        ['height', []],
        ['width', []],
        ['depth', []],
        ['weight', []],
    ]),
};
